<?php

namespace GS_TECA;

/**
 * Protect direct access
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Flatsome UX Builder element for rendering saved TECA shortcodes.
 */
class Teca_UX_Builder_Events_Element {

	/**
	 * UX Builder element shortcode slug.
	 *
	 * @var string
	 */
	const BASE = 'teca_ux_builder_events';

	/**
	 * Register the frontend/editor shortcode.
	 *
	 * @return void
	 */
	public static function register_shortcode() {
		if ( shortcode_exists( self::BASE ) ) {
			return;
		}

		add_shortcode( self::BASE, [ __CLASS__, 'render_element' ] );
	}

	/**
	 * Register the UX Builder element definition.
	 *
	 * @return void
	 */
	public static function register_ux_builder_element() {
		if ( ! function_exists( 'add_ux_builder_shortcode' ) ) {
			return;
		}

		add_ux_builder_shortcode(
			self::BASE,
			[
				'name'        => esc_html__( 'TECA Events', 'the-events-calendar-addon' ),
				'category'    => esc_html__( 'GS Plugins', 'the-events-calendar-addon' ),
				'thumbnail'   => esc_url( GS_TECA_PLUGIN_URI . 'assets/img/events.svg' ),
				'description' => esc_html__( 'Display TECA events/layouts using saved TECA shortcodes.', 'the-events-calendar-addon' ),
				'wrap'        => false,
				'options'     => [
					'shortcode_id' => [
						'type'        => 'select',
						'heading'     => esc_html__( 'Select TECA Shortcode', 'the-events-calendar-addon' ),
						'default'     => self::get_default_shortcode_value(),
						'options'     => teca_get_saved_shortcodes_for_ux_builder(),
						'description' => self::get_field_description(),
						'full_width'  => true,
					],
				],
			]
		);
	}

	/**
	 * Render UX Builder element output.
	 *
	 * @param array<string, mixed>|string $atts Shortcode attributes.
	 * @return string
	 */
	public static function render_element( $atts ) {
		$atts = shortcode_atts(
			[
				'shortcode_id' => '',
			],
			(array) $atts,
			self::BASE
		);

		$shortcode_id = ! empty( $atts['shortcode_id'] ) ? absint( $atts['shortcode_id'] ) : 0;

		if ( ! $shortcode_id ) {
			$shortcode_id = absint( self::get_default_shortcode_value() );
		}

		$allow_placeholder = self::is_editor_context();

		if ( ! $shortcode_id ) {
			return $allow_placeholder
				? '<div class="teca-ux-builder-placeholder">' . esc_html__( 'Please select a TECA shortcode.', 'the-events-calendar-addon' ) . '</div>'
				: '';
		}

		if ( ! teca_shortcode_exists( $shortcode_id ) ) {
			return $allow_placeholder
				? '<div class="teca-ux-builder-placeholder">' . esc_html__( 'Selected TECA shortcode was not found.', 'the-events-calendar-addon' ) . '</div>'
				: '';
		}

		$output = teca_render_saved_shortcode( $shortcode_id );

		return sprintf(
			'<div class="teca-ux-builder-widget-wrap" data-teca-ux-builder-shortcode="%1$s">%2$s</div>',
			esc_attr( (string) $shortcode_id ),
			$output // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- shortcode HTML is generated by TECA.
		);
	}

	/**
	 * Whether the request is a UX Builder editor context.
	 *
	 * @return bool
	 */
	protected static function is_editor_context() {
		if ( function_exists( 'ux_builder_is_active' ) && ux_builder_is_active() ) {
			return true;
		}

		if ( function_exists( 'ux_builder_is_doing_shortcode' ) && ux_builder_is_doing_shortcode() ) {
			return true;
		}

		if ( ! empty( $_GET['uxb_iframe'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return true;
		}

		if ( ! empty( $_GET['app'] ) && 'uxbuilder' === $_GET['app'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return true;
		}

		if ( function_exists( __NAMESPACE__ . '\\plugin' ) && plugin()->integrations && plugin()->integrations->is_builder_preview() ) {
			return true;
		}

		return false;
	}

	/**
	 * Control field description with edit/create links.
	 *
	 * @return string
	 */
	protected static function get_field_description() {
		$edit_link = sprintf(
			'%s: <a class="teca-ux-builder-edit-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Edit this shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode/' ) ),
			esc_html__( 'Edit', 'the-events-calendar-addon' )
		);

		$create_link = sprintf(
			'%s: <a class="teca-ux-builder-create-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Create new shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode' ) ),
			esc_html__( 'Create', 'the-events-calendar-addon' )
		);

		return implode( '<br />', [ $edit_link, $create_link ] );
	}

	/**
	 * Default dropdown value.
	 *
	 * @return string
	 */
	protected static function get_default_shortcode_value() {
		$options = teca_get_saved_shortcodes_for_ux_builder();

		if ( empty( $options ) ) {
			return '';
		}

		foreach ( $options as $value => $label ) {
			if ( '' === (string) $value ) {
				continue;
			}

			return (string) absint( $value );
		}

		return '';
	}
}
