<?php

// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedNamespaceFound -- Existing plugin namespace is intentionally kept for backward compatibility.
namespace GS_TECA;

/**
 * Protect direct access
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( '\Elementor\Widget_Base' ) ) {
	return;
}

/**
 * Elementor widget for rendering saved TECA shortcodes.
 */
class Teca_Elementor_Events_Widget extends \Elementor\Widget_Base {

	/**
	 * Widget slug.
	 *
	 * @return string
	 */
	public function get_name() {
		return 'teca-events';
	}

	/**
	 * Widget title.
	 *
	 * @return string
	 */
	public function get_title() {
		return esc_html__( 'TECA Events', 'the-events-calendar-addon' );
	}

	/**
	 * Widget icon class.
	 *
	 * @return string
	 */
	public function get_icon() {
		return 'teca-events';
	}

	/**
	 * Widget categories.
	 *
	 * @return string[]
	 */
	public function get_categories() {
		return [ 'gs-plugins', 'general' ];
	}

	/**
	 * Widget keywords.
	 *
	 * @return string[]
	 */
	public function get_keywords() {
		return [ 'teca', 'events', 'calendar', 'shortcode' ];
	}

	/**
	 * Register widget controls.
	 *
	 * @return void
	 */
	protected function register_controls() {
		$this->start_controls_section(
			'content_section',
			[
				'label' => esc_html__( 'Content', 'the-events-calendar-addon' ),
				'tab'   => \Elementor\Controls_Manager::TAB_CONTENT,
			]
		);

		$this->add_control(
			'shortcode_id',
			[
				'label'       => esc_html__( 'TECA Shortcode', 'the-events-calendar-addon' ),
				'description' => $this->get_field_description(),
				'label_block' => true,
				'type'        => \Elementor\Controls_Manager::SELECT,
				'options'     => $this->get_shortcode_options(),
				'default'     => $this->get_default_shortcode_id(),
			]
		);

		$this->end_controls_section();
	}

	/**
	 * Control field description with edit/create links.
	 *
	 * @return string
	 */
	protected function get_field_description() {
		$edit_link = sprintf(
			'%s: <a class="teca-elementor-edit-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Edit this shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode/' ) ),
			esc_html__( 'Edit', 'the-events-calendar-addon' )
		);

		$create_link = sprintf(
			'%s: <a class="teca-elementor-create-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Create new shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode' ) ),
			esc_html__( 'Create', 'the-events-calendar-addon' )
		);

		return implode( '<br />', [ $edit_link, $create_link ] );
	}

	/**
	 * Shortcode select options.
	 *
	 * @return array<int|string, string>
	 */
	protected function get_shortcode_options() {
		$options = teca_get_saved_shortcodes_for_builder();

		if ( ! empty( $options ) ) {
			return $options;
		}

		return [
			'' => esc_html__( 'No TECA shortcode found', 'the-events-calendar-addon' ),
		];
	}

	/**
	 * Default shortcode ID.
	 *
	 * @return string
	 */
	protected function get_default_shortcode_id() {
		$options = teca_get_saved_shortcodes_for_builder();

		if ( empty( $options ) ) {
			return '';
		}

		$ids = array_keys( $options );

		return (string) absint( reset( $ids ) );
	}

	/**
	 * Render widget output.
	 *
	 * @return void
	 */
	protected function render() {
		$settings     = $this->get_settings_for_display();
		$shortcode_id = ! empty( $settings['shortcode_id'] ) ? absint( $settings['shortcode_id'] ) : 0;

		if ( ! $shortcode_id ) {
			$shortcode_id = absint( $this->get_default_shortcode_id() );
		}

		if ( $this->is_editor_placeholder_context() ) {
			if ( ! $shortcode_id ) {
				$this->render_placeholder( esc_html__( 'Please select a TECA shortcode.', 'the-events-calendar-addon' ) );
				return;
			}

			if ( ! teca_shortcode_exists( $shortcode_id ) ) {
				$this->render_placeholder( esc_html__( 'Selected TECA shortcode was not found.', 'the-events-calendar-addon' ) );
				return;
			}
		} elseif ( ! $shortcode_id || ! teca_shortcode_exists( $shortcode_id ) ) {
			return;
		}

		echo '<div class="teca-elementor-widget-wrap" data-teca-elementor-shortcode="' . esc_attr( (string) $shortcode_id ) . '">';
		echo do_shortcode( sprintf( '[gs-teca id="%d"]', $shortcode_id ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- shortcode HTML is generated by TECA.
		echo '</div>';
	}

	/**
	 * Whether the widget is rendering inside Elementor editor/preview.
	 *
	 * @return bool
	 */
	protected function is_editor_placeholder_context() {
		if ( ! class_exists( '\Elementor\Plugin' ) ) {
			return false;
		}

		$elementor = \Elementor\Plugin::$instance;

		if ( isset( $elementor->editor ) && $elementor->editor->is_edit_mode() ) {
			return true;
		}

		if ( isset( $elementor->preview ) && $elementor->preview->is_preview_mode() ) {
			return true;
		}

		return false;
	}

	/**
	 * Output editor placeholder markup.
	 *
	 * @param string $message Placeholder message.
	 * @return void
	 */
	protected function render_placeholder( $message ) {
		echo '<div class="teca-elementor-placeholder">' . esc_html( $message ) . '</div>';
	}
}
