<?php

/**
 * Beaver Builder module frontend template.
 *
 * @var GS_TECA\Teca_Beaver_Events_Module $module Module instance.
 * @var object                            $settings Module settings.
 */

use function GS_TECA\plugin;
use function GS_TECA\teca_render_saved_shortcode;
use function GS_TECA\teca_shortcode_exists;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- Variables are intentionally local to this Beaver Builder frontend template and shared with the module partial.
$shortcode_id      = ! empty( $settings->shortcode_id ) ? absint( $settings->shortcode_id ) : 0;
$allow_placeholder = false;

if ( class_exists( 'FLBuilderModel' ) && FLBuilderModel::is_builder_active() ) {
	$allow_placeholder = true;
} elseif ( function_exists( 'GS_TECA\plugin' ) && plugin()->integrations ) {
	$allow_placeholder = (bool) plugin()->integrations->is_builder_preview();
}

if ( ! $shortcode_id ) {
	if ( $allow_placeholder ) {
		echo '<div class="teca-beaver-placeholder">' . esc_html__( 'Please select a TECA shortcode.', 'the-events-calendar-addon2' ) . '</div>';
	}
	return;
}

if ( ! teca_shortcode_exists( $shortcode_id ) ) {
	if ( $allow_placeholder ) {
		echo '<div class="teca-beaver-placeholder">' . esc_html__( 'Selected TECA shortcode was not found.', 'the-events-calendar-addon2' ) . '</div>';
	}
	return;
}

$output = teca_render_saved_shortcode( $shortcode_id );

printf(
	'<div class="teca-beaver-widget-wrap" data-teca-beaver-shortcode="%1$s">%2$s</div>',
	esc_attr( (string) $shortcode_id ),
	$output // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- shortcode HTML is generated by TECA.
);
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
