<?php

/**
 * Protect direct access
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'OxyEl' ) ) {
	return;
}

/**
 * Oxygen Builder element for rendering saved TECA shortcodes.
 */
class TECA_Oxygen_Events_Element extends OxyEl {

	/**
	 * Register element hooks.
	 *
	 * @return void
	 */
	public function init() {
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_scripts' ] );
	}

	/**
	 * Enqueue TECA assets inside the Oxygen builder iframe.
	 *
	 * @return void
	 */
	public function enqueue_scripts() {
		if ( empty( $_GET['ct_builder'] ) || empty( $_GET['oxygen_iframe'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}

		if ( ! function_exists( 'GS_TECA\plugin' ) ) {
			return;
		}

		GS_TECA\plugin()->scripts->wp_enqueue_style_all( 'public', [ 'gs-teca-divi-public' ] );
		GS_TECA\plugin()->scripts->wp_enqueue_script_all( 'public' );

		if ( function_exists( 'GS_TECA\gsTecaAssetGenerator' ) ) {
			GS_TECA\gsTecaAssetGenerator()->enqueue_prefs_custom_css();
			GS_TECA\gsTecaAssetGenerator()->enqueue_localize_script();
		}

		wp_enqueue_script(
			'gs-teca-oxygen-editor',
			GS_TECA_PLUGIN_URI . 'includes/integration/oxygen/assets/js/teca-oxygen-editor.js',
			[ 'jquery' ],
			GS_TECA_VERSION,
			true
		);
	}

	/**
	 * Element name.
	 *
	 * @return string
	 */
	public function name() {
		return esc_html__( 'TECA Events', 'the-events-calendar-addon' );
	}

	/**
	 * Element slug.
	 *
	 * @return string
	 */
	public function slug() {
		return 'teca-oxygen-events';
	}

	/**
	 * Element icon.
	 *
	 * @return string
	 */
	public function icon() {
		return GS_TECA_PLUGIN_URI . 'assets/img/events.svg';
	}

	/**
	 * Render element output.
	 *
	 * @param array<string, mixed> $options Element options.
	 * @return void
	 */
	public function render( $options ) {
		$shortcode_id      = ! empty( $options['shortcode_id'] ) ? absint( $options['shortcode_id'] ) : 0;
		$allow_placeholder = $this->is_oxygen_builder_context();

		if ( ! $shortcode_id ) {
			if ( $allow_placeholder ) {
				echo '<div class="teca-oxygen-placeholder">' . esc_html__( 'Please select a TECA shortcode.', 'the-events-calendar-addon' ) . '</div>';
			}
			return;
		}

		if ( ! GS_TECA\teca_shortcode_exists( $shortcode_id ) ) {
			if ( $allow_placeholder ) {
				echo '<div class="teca-oxygen-placeholder">' . esc_html__( 'Selected TECA shortcode was not found.', 'the-events-calendar-addon' ) . '</div>';
			}
			return;
		}

		echo '<div class="teca-oxygen-widget-wrap" data-teca-oxygen-shortcode="' . esc_attr( (string) $shortcode_id ) . '">';
		echo GS_TECA\teca_render_saved_shortcode( $shortcode_id ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- shortcode HTML is generated by TECA.
		echo '</div>';
	}

	/**
	 * Element controls.
	 *
	 * @return void
	 */
	public function controls() {
		$this->addOptionControl(
			[
				'type' => 'dropdown',
				'name' => esc_html__( 'Select TECA Shortcode', 'the-events-calendar-addon' ),
				'slug' => 'shortcode_id',
			]
		)->setValue( $this->get_shortcode_dropdown_values() )->rebuildElementOnChange();
	}

	/**
	 * Dropdown values for Oxygen controls.
	 *
	 * @return array<int|string, string>
	 */
	protected function get_shortcode_dropdown_values() {
		$values = GS_TECA\teca_get_saved_shortcodes_for_oxygen();

		if ( ! empty( $values ) ) {
			return $values;
		}

		return [
			'' => esc_html__( 'No TECA shortcode found', 'the-events-calendar-addon' ),
		];
	}

	/**
	 * Whether the element is rendering inside Oxygen builder.
	 *
	 * @return bool
	 */
	protected function is_oxygen_builder_context() {
		if ( ! empty( $_GET['ct_builder'] ) && ! empty( $_GET['oxygen_iframe'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return true;
		}

		return false;
	}
}
