<?php

// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedNamespaceFound -- Existing plugin namespace is intentionally kept for backward compatibility.
namespace GS_TECA;

/**
 * Protect direct access
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * WPBakery element for rendering saved TECA shortcodes.
 */
class Teca_WPBakery_Events_Element {

	/**
	 * WPBakery element base slug.
	 *
	 * @var string
	 */
	const BASE = 'teca_wpbakery_events';

	/**
	 * Register WPBakery map and wrapper shortcode.
	 *
	 * @return void
	 */
	public static function register() {
		if ( ! function_exists( 'vc_map' ) ) {
			return;
		}

		if ( ! shortcode_exists( self::BASE ) ) {
			add_shortcode( self::BASE, [ __CLASS__, 'render_element' ] );
		}

		vc_map(
			[
				'name'        => esc_html__( 'TECA Events', 'the-events-calendar-addon' ),
				'base'        => self::BASE,
				'category'    => esc_html__( 'GS Plugins', 'the-events-calendar-addon' ),
				'description' => esc_html__( 'Display TECA events using a saved shortcode.', 'the-events-calendar-addon' ),
				'icon'        => 'icon-teca-wpbakery-events',
				'params'      => [
					[
						'type'        => 'dropdown',
						'heading'     => esc_html__( 'Select TECA Shortcode', 'the-events-calendar-addon' ),
						'param_name'  => 'shortcode_id',
						'value'       => self::get_shortcode_dropdown_values(),
						'std'         => self::get_default_shortcode_value(),
						'description' => self::get_field_description(),
						'admin_label' => true,
					],
				],
			]
		);
	}

	/**
	 * Element base slug.
	 *
	 * @return string
	 */
	public static function get_base() {
		return self::BASE;
	}

	/**
	 * Render WPBakery element output.
	 *
	 * @param array<string, mixed>|string $atts Shortcode attributes.
	 * @return string
	 */
	public static function render_element( $atts ) {
		$atts = shortcode_atts(
			[
				'shortcode_id' => '',
			],
			(array) $atts,
			self::BASE
		);

		$shortcode_id = ! empty( $atts['shortcode_id'] ) ? absint( $atts['shortcode_id'] ) : 0;

		if ( ! $shortcode_id ) {
			$shortcode_id = absint( self::get_default_shortcode_value() );
		}

		$allow_placeholder = self::is_editor_context();

		if ( ! $shortcode_id ) {
			return $allow_placeholder
				? '<div class="teca-wpbakery-placeholder">' . esc_html__( 'Please select a TECA shortcode.', 'the-events-calendar-addon' ) . '</div>'
				: '';
		}

		if ( ! teca_shortcode_exists( $shortcode_id ) ) {
			return $allow_placeholder
				? '<div class="teca-wpbakery-placeholder">' . esc_html__( 'Selected TECA shortcode was not found.', 'the-events-calendar-addon' ) . '</div>'
				: '';
		}

		$output = do_shortcode( sprintf( '[gs-teca id="%d"]', $shortcode_id ) );

		return sprintf(
			'<div class="teca-wpbakery-widget-wrap" data-teca-wpbakery-shortcode="%1$s">%2$s</div>',
			esc_attr( (string) $shortcode_id ),
			$output // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- shortcode HTML is generated by TECA.
		);
	}

	/**
	 * Whether the request is a WPBakery editor context.
	 *
	 * @return bool
	 */
	protected static function is_editor_context() {
		if ( ! empty( $_GET['vc_editable'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return true;
		}

		if ( function_exists( 'vc_is_inline' ) && vc_is_inline() ) {
			return true;
		}

		if ( function_exists( 'vc_is_frontend_editor' ) && vc_is_frontend_editor() ) {
			return true;
		}

		return false;
	}

	/**
	 * Control field description with edit/create links.
	 *
	 * @return string
	 */
	protected static function get_field_description() {
		$edit_link = sprintf(
			'%s: <a class="teca-wpbakery-edit-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Edit this shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode/' ) ),
			esc_html__( 'Edit', 'the-events-calendar-addon' )
		);

		$create_link = sprintf(
			'%s: <a class="teca-wpbakery-create-link" href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
			esc_html__( 'Create new shortcode', 'the-events-calendar-addon' ),
			esc_url( admin_url( 'admin.php?page=gs-the-events-calendar-addon#/shortcode' ) ),
			esc_html__( 'Create', 'the-events-calendar-addon' )
		);

		return implode( '<br />', [ $edit_link, $create_link ] );
	}

	/**
	 * WPBakery dropdown values (title => id).
	 *
	 * @return array<string, string>
	 */
	protected static function get_shortcode_dropdown_values() {
		$values = teca_get_saved_shortcodes_for_wpbakery();

		return ! empty( $values ) ? $values : [
			esc_html__( 'No TECA shortcode found', 'the-events-calendar-addon' ) => '',
		];
	}

	/**
	 * Default dropdown value.
	 *
	 * @return string
	 */
	protected static function get_default_shortcode_value() {
		$values = teca_get_saved_shortcodes_for_wpbakery();

		if ( empty( $values ) ) {
			return '';
		}

		$ids = array_values( $values );

		return (string) absint( reset( $ids ) );
	}
}
